### ISSUE TITLE
Tutorial on how to use QuickPlot

### ISSUE THREAD

**Issue by schiegl** [tepf/QuickPlot#5]
A tutorial on how to use it and how I created the Atom setup in the demo is missing.

**Comment by octopuscabbage** [comment]
I might write an example using https://data.mo.gov/Labor/Missouri-Monthly-Unemployment-Claims-By-Industry/cj66-t7xq on my blog, I'll link it if I actually do it.

**Comment by schiegl** [comment]
That would be nice. But don't be too quick as the API is still quite prone to change. It might confuse people.

**Comment by schiegl** [comment]
I added [BasicPlotting.lhs](https://github.com/tepf/QuickPlot/blob/master/examples/BasicPlotting.lhs) to the project which is a bit of a walkthrough, through some of the functionality.
